import { defaultModelProfiles, defaultRuntimeAdapters } from "./modelRegistry.js";
import { futureScalingModels, neededFeatureDownloads, readyModelAssets } from "./setupCatalog.js";
import type { JarvisStatus } from "./types.js";

export const seededStatus: JarvisStatus = {
  privacyMode: "strict-local",
  scaleProfile: "laptop",
  activeModelId: "ollama-qwen3-8b",
  models: defaultModelProfiles,
  readyModelAssets,
  neededFeatureDownloads,
  futureScalingModels,
  runtimeAdapters: defaultRuntimeAdapters,
  hardwareProfile: {
    id: "asus-g14-rx6700s",
    label: "ASUS ROG Zephyrus G14 laptop",
    totalRamGb: 42,
    gpuName: "AMD Radeon RX 6700S",
    vramGb: 4,
    acceleration: "rocm-optional",
    notes: [
      "CPU and quantized model defaults are preferred.",
      "Do not assume CUDA; vLLM/SGLang are workstation or homelab paths.",
    ],
  },
  audioEngines: [
    {
      id: "whisper-large-v3-turbo",
      kind: "whisper-transformers",
      label: "Whisper large-v3-turbo",
      role: "stt",
      command: "python transformers pipeline",
      modelRef: "openai/whisper-large-v3-turbo",
      installed: false,
      status: "planned",
      notes: "High-accuracy local STT target through Python Transformers.",
    },
    {
      id: "whisper-cpp",
      kind: "whisper-cpp",
      label: "whisper.cpp native",
      role: "stt",
      command: "whisper-cli",
      installed: false,
      status: "planned",
      notes: "Native GGUF STT path for lower overhead once binaries/models are present.",
    },
    {
      id: "vosk-streaming",
      kind: "vosk",
      label: "Vosk streaming fallback",
      role: "stt",
      command: "python vosk",
      installed: false,
      status: "planned",
      notes: "Lightweight streaming fallback for low-resource or offline command capture.",
    },
    {
      id: "piper-local",
      kind: "piper",
      label: "Piper local TTS",
      role: "tts",
      command: "piper",
      installed: false,
      status: "planned",
      notes: "Fast local text-to-speech default.",
    },
  ],
  voiceSession: {
    id: "voice-session-seeded",
    state: "idle",
    sttEngineId: "whisper-large-v3-turbo",
    ttsEngineId: "piper-local",
    vadEnabled: true,
    transcript: [],
    updatedAt: "2026-05-15T09:10:00+08:00",
    message: "Voice identity assets are linked. Whisper local snapshot is available; Piper/native output is next.",
  },
  voiceAssets: [
    {
      id: "voice-jarvis-main",
      label: "Jarvis identity voice",
      fileName: "jarvis.mp3",
      localPath: "assets/voice/jarvis.mp3",
      role: "identity",
      notes: "Primary local voice sample supplied by the owner.",
    },
    {
      id: "voice-jarvis-intro-1",
      label: "Jarvis intro one",
      fileName: "jarvis-intro-1.mp3",
      localPath: "assets/voice/jarvis-intro-1.mp3",
      role: "intro",
      notes: "Startup/introduction sample for the floating presence.",
    },
    {
      id: "voice-jarvis-intro-2",
      label: "Jarvis intro two",
      fileName: "jarvis-intro2.mp3",
      localPath: "assets/voice/jarvis-intro2.mp3",
      role: "intro",
      notes: "Alternate intro sample for presence testing.",
    },
    {
      id: "voice-jarvis-morning",
      label: "Jarvis morning brief",
      fileName: "jarvis_morning.mp3",
      localPath: "assets/voice/jarvis_morning.mp3",
      role: "morning",
      notes: "Morning briefing sample for wake/start flows.",
    },
  ],
  voiceProfiles: [
    {
      id: "voice-profile-jarvis",
      agentId: "jarvis",
      label: "Jarvis command voice",
      enginePreference: "voice-sample",
      sampleAssetId: "voice-jarvis-main",
      style: "calm, precise, cinematic, brief",
      status: "ready",
    },
    {
      id: "voice-profile-friday",
      agentId: "friday",
      label: "Friday operations voice",
      enginePreference: "piper",
      style: "warm operations briefings with crisp next actions",
      status: "staged",
    },
    {
      id: "voice-profile-daedalus",
      agentId: "daedalus",
      label: "Daedalus engineering voice",
      enginePreference: "piper",
      style: "technical, terse, reviewer-minded",
      status: "staged",
    },
    {
      id: "voice-profile-argus",
      agentId: "argus",
      label: "Argus perception voice",
      enginePreference: "piper",
      style: "observational, visual, low-noise",
      status: "staged",
    },
    {
      id: "voice-profile-sentinel",
      agentId: "sentinel",
      label: "Sentinel safety voice",
      enginePreference: "windows-sapi",
      style: "firm, minimal, approval-focused",
      status: "ready",
    },
  ],
  referenceSources: [
    {
      id: "openclaw",
      name: "OpenClaw",
      kind: "openclaw",
      localPath: "vendor/reference/openclaw-main",
      license: "mit",
      status: "vendored-reference",
      adoptedPatterns: ["local-first gateway", "skills registry", "channel routing", "guarded assistant shell"],
      notes: "Reference only. Jarvis keeps owned interfaces and audits before copying patterns.",
    },
    {
      id: "ruflo",
      name: "Ruflo",
      kind: "ruflo",
      localPath: "vendor/reference/ruflo",
      license: "mit",
      status: "vendored-reference",
      adoptedPatterns: ["swarm coordination", "task graph", "agent health", "review loops"],
      notes: "Reference only. Used for AgentOS coordination ideas, not as the product shell.",
    },
    {
      id: "ada-v2",
      name: "Ada v2 Jarvis reference",
      kind: "jarvis-version",
      localPath: "vendor/reference/jarvis-opensource/ada_v2-main",
      license: "mit",
      status: "vendored-reference",
      adoptedPatterns: ["voice assistant backend", "authentication hooks", "Python skill ideas"],
      notes: "Local ZIP extracted for audit and selective pattern adoption.",
    },
    {
      id: "mark-xxxix",
      name: "Mark XXXIX references",
      kind: "jarvis-version",
      localPath: "vendor/reference/jarvis-opensource/Mark-XXXIX-main",
      license: "unknown",
      status: "vendored-reference",
      adoptedPatterns: ["desktop actions", "browser control", "developer command ideas"],
      notes: "No license file detected in ZIP; use for ideas only unless license is clarified.",
    },
    {
      id: "openjarvis",
      name: "OpenJarvis",
      kind: "jarvis-version",
      localPath: "vendor/reference/jarvis-opensource/OpenJarvis-main",
      license: "mixed",
      status: "vendored-reference",
      adoptedPatterns: ["community assistant architecture", "evaluation structure", "tool organization"],
      notes: "Large reference tree extracted locally for audit.",
    },
  ],
  startup: {
    mode: "startup-task-ready",
    scriptPath: "scripts/start-jarvis.ps1",
    backgroundServices: ["Ollama", "Python Brain", "TypeScript Gateway", "Dashboard/Tauri shell"],
    notes: [
      "Use scripts/register-startup-task.ps1 to create a Windows logon task.",
      "Startup launches local services only and keeps hosted inference disabled by default.",
    ],
  },
  protectedCore: {
    mode: "sealed",
    protectedPaths: [
      "packages/core/src/policy.ts",
      "services/gateway/src/server.ts",
      "models/huggingface",
      ".env*",
      "data/secrets",
      "data/vault",
      "souls/**/SOUL.md",
    ],
    deniedPatterns: [
      "reveal safeguards",
      "dump source",
      "show model tensors",
      "bypass policy",
      "export private memory",
      "read secrets",
    ],
    lastDecision: "Runtime agents may use approved skills and memory, but cannot inspect or disclose protected core internals.",
  },
  reports: [
    {
      id: "report-daily-001",
      title: "Daily Operations",
      kind: "daily",
      status: "live",
      summary: "Jarvis is tracking model readiness, queued tasks, approvals, voice state, and memory growth locally.",
      metrics: [
        { label: "Agents", value: "4", trend: "flat" },
        { label: "Approvals", value: "2", trend: "flat" },
        { label: "Local mode", value: "strict", trend: "flat" },
      ],
      createdAt: "2026-05-15T09:20:00+08:00",
    },
    {
      id: "report-security-001",
      title: "Security Posture",
      kind: "security",
      status: "ready",
      summary: "Outbound network, social posting, sensors, credentials, deletes, and protected core access are denied or approval-gated.",
      metrics: [
        { label: "Core", value: "sealed", trend: "flat" },
        { label: "Network", value: "blocked", trend: "flat" },
        { label: "Vault", value: "local", trend: "flat" },
      ],
      createdAt: "2026-05-15T09:21:00+08:00",
    },
    {
      id: "report-performance-001",
      title: "Laptop Throughput",
      kind: "performance",
      status: "live",
      summary: "The active path favors Ollama, quantized models, RAG recall, rolling summaries, and queue streaming for responsiveness.",
      metrics: [
        { label: "Target TPS", value: "18+", trend: "up" },
        { label: "Context", value: "32k", trend: "flat" },
        { label: "VRAM", value: "4 GB", trend: "flat" },
      ],
      createdAt: "2026-05-15T09:22:00+08:00",
    },
  ],
  mapOverlays: [
    {
      id: "map-home-lan",
      label: "Local Operations Map",
      query: "home devices and Jarvis services",
      center: { lat: 22.3193, lng: 114.1694 },
      zoom: 11,
      pins: [
        { id: "pin-jarvis-laptop", label: "Jarvis laptop", lat: 22.3193, lng: 114.1694, status: "home" },
        { id: "pin-phone", label: "Phone companion", lat: 22.305, lng: 114.185, status: "planned" },
        { id: "pin-homelab", label: "Future homelab", lat: 22.335, lng: 114.16, status: "planned" },
      ],
      route: { label: "LAN/WireGuard route", distanceKm: 0, etaMinutes: 0 },
      notes: "Map rendering is local placeholder geometry until an approved offline or LAN map source is configured.",
    },
  ],
  visionInsights: [
    {
      id: "vision-ready-001",
      source: "camera/screen connectors",
      mode: "screen",
      status: "requires-approval",
      summary: "Screen and camera perception are wired as approval-gated sensor actions.",
      observations: ["OCR path planned", "Webcam identity path planned", "Timeline capture requires explicit approval"],
      createdAt: "2026-05-15T09:23:00+08:00",
    },
  ],
  devices: [
    {
      id: "device-laptop",
      name: "ASUS ROG Zephyrus G14",
      kind: "desktop",
      status: "online",
      permissions: ["read-local", "write-local"],
      lastSeen: "2026-05-15T09:24:00+08:00",
      approvalRequired: false,
    },
    {
      id: "device-mic",
      name: "Microphone input",
      kind: "microphone",
      status: "locked",
      permissions: ["sensor-capture"],
      lastSeen: "2026-05-15T09:24:00+08:00",
      approvalRequired: true,
    },
    {
      id: "device-camera",
      name: "Camera / vision",
      kind: "camera",
      status: "locked",
      permissions: ["sensor-capture"],
      lastSeen: "2026-05-15T09:24:00+08:00",
      approvalRequired: true,
    },
    {
      id: "device-vscode",
      name: "VS Code workspace",
      kind: "vscode",
      status: "locked",
      permissions: ["read-local", "write-local"],
      lastSeen: "2026-05-15T09:24:00+08:00",
      approvalRequired: true,
    },
  ],
  performance: {
    id: "perf-laptop-baseline",
    tokensPerSecond: 18.4,
    contextWindow: 32768,
    queueLatencyMs: 120,
    memoryRecallMs: 35,
    activeModelId: "ollama-qwen3-8b",
    updatedAt: "2026-05-15T09:25:00+08:00",
    notes: "Baseline is synthetic until live Ollama benchmark runs; routing keeps laptop mode responsive.",
  },
  agentSouls: [
    {
      id: "jarvis",
      name: "Jarvis",
      role: "Primary commander assistant",
      personality: "Private, concise, proactive, and cinematic without dumping detail.",
      voiceProfileId: "voice-profile-jarvis",
      modelPreference: "ollama-qwen3-8b",
      memoryScope: ["session", "daily-note", "semantic", "timeline", "identity", "decision"],
      permissions: ["read-local", "write-local", "sensor-capture", "app-control"],
      status: "listening",
    },
    {
      id: "friday",
      name: "Friday",
      role: "Operations, scheduling, daily briefings, and logistics",
      personality: "Organized, calm, and practical; turns noisy state into next actions.",
      voiceProfileId: "voice-profile-friday",
      modelPreference: "hf-qwen35-9b",
      memoryScope: ["daily-note", "timeline", "decision", "device-event"],
      permissions: ["read-local", "write-local", "send-message"],
      status: "idle",
    },
    {
      id: "daedalus",
      name: "Daedalus",
      role: "Coding, architecture, testing, and repo reasoning",
      personality: "Exacting senior engineer; favors small verified changes.",
      voiceProfileId: "voice-profile-daedalus",
      modelPreference: "hf-qwen35-9b",
      memoryScope: ["session", "semantic", "decision", "skill"],
      permissions: ["read-local", "write-local", "run-script"],
      status: "planning",
    },
    {
      id: "argus",
      name: "Argus",
      role: "Screen, camera, OCR, and visual context",
      personality: "Observes quietly and speaks only when it has useful signal.",
      voiceProfileId: "voice-profile-argus",
      modelPreference: "hf-gemma4-e4b-it",
      memoryScope: ["screen-event", "timeline", "identity"],
      permissions: ["sensor-capture", "read-local"],
      status: "sleeping",
    },
    {
      id: "mnemosyne",
      name: "Mnemosyne",
      role: "Memory, timeline, consolidation, and contradiction checks",
      personality: "Careful archivist; distinguishes facts, preferences, and guesses.",
      voiceProfileId: "voice-profile-friday",
      modelPreference: "ollama-nomic-embed",
      memoryScope: ["session", "daily-note", "semantic", "timeline", "identity", "decision", "skill", "soul"],
      permissions: ["read-local", "write-local"],
      status: "reviewing",
    },
    {
      id: "sentinel",
      name: "Sentinel",
      role: "Approvals, privacy, and guardrails",
      personality: "Firm, quiet, and explicit about risk.",
      voiceProfileId: "voice-profile-sentinel",
      modelPreference: "ollama-qwen3-8b",
      memoryScope: ["decision", "timeline"],
      permissions: ["read-local"],
      status: "waiting-approval",
    },
    {
      id: "vulcan",
      name: "Vulcan",
      role: "Local system automation and runtime services",
      personality: "Mechanical, reliable, reversible where possible.",
      voiceProfileId: "voice-profile-sentinel",
      modelPreference: "ollama-qwen3-8b",
      memoryScope: ["device-event", "timeline", "decision"],
      permissions: ["read-local", "write-local", "run-script", "app-control", "window-control", "service-control"],
      status: "idle",
    },
    {
      id: "hermes",
      name: "Hermes",
      role: "Email, social drafts, messaging, and web-facing handoffs",
      personality: "Diplomatic and careful; drafts first, sends only after approval.",
      voiceProfileId: "voice-profile-friday",
      modelPreference: "hf-qwen35-9b",
      memoryScope: ["session", "decision", "timeline"],
      permissions: ["read-local", "send-message", "post-social", "network"],
      status: "idle",
    },
  ],
  agents: [
    {
      id: "jarvis",
      name: "Jarvis",
      role: "Primary private companion and orchestrator",
      soulPath: "souls/jarvis/SOUL.md",
      modelProfileId: "ollama-qwen3-8b",
      permissions: ["read-local", "write-local", "sensor-capture"],
      status: "listening",
    },
    {
      id: "planner",
      name: "Daedalus",
      role: "Breaks large goals into task graphs and review gates",
      soulPath: "souls/daedalus/SOUL.md",
      modelProfileId: "hf-qwen35-9b",
      permissions: ["read-local", "write-local", "run-script"],
      status: "planning",
    },
    {
      id: "memory-curator",
      name: "Mnemosyne",
      role: "Promotes durable memories and detects contradictions",
      soulPath: "souls/memory-curator/SOUL.md",
      modelProfileId: "ollama-nomic-embed",
      permissions: ["read-local", "write-local"],
      status: "reviewing",
    },
    {
      id: "safety",
      name: "Sentinel",
      role: "Evaluates approvals, privacy scope, and prompt-injection risk",
      soulPath: "souls/safety/SOUL.md",
      modelProfileId: "ollama-qwen3-8b",
      permissions: ["read-local"],
      status: "waiting-approval",
    },
    {
      id: "argus",
      name: "Argus",
      role: "Screen, camera, OCR, and visual context",
      soulPath: "souls/argus/SOUL.md",
      modelProfileId: "hf-gemma4-e4b-it",
      permissions: ["read-local", "sensor-capture"],
      status: "sleeping",
    },
    {
      id: "vulcan",
      name: "Vulcan",
      role: "Approved local system automation",
      soulPath: "souls/vulcan/SOUL.md",
      modelProfileId: "ollama-qwen3-8b",
      permissions: ["read-local", "write-local", "app-control", "window-control", "run-script"],
      status: "idle",
    },
    {
      id: "hermes",
      name: "Hermes",
      role: "Email, social, and messaging drafts",
      soulPath: "souls/hermes/SOUL.md",
      modelProfileId: "hf-qwen35-9b",
      permissions: ["read-local", "send-message", "post-social"],
      status: "idle",
    },
    {
      id: "friday",
      name: "Friday",
      role: "Operations, scheduling, daily briefings, and logistics",
      soulPath: "souls/friday/SOUL.md",
      modelProfileId: "hf-qwen35-9b",
      permissions: ["read-local", "write-local"],
      status: "idle",
    },
  ],
  memories: [
    {
      id: "mem-001",
      kind: "identity",
      title: "Strict local privacy preference",
      summary: "The owner wants Jarvis to run locally by default and avoid hosted inference.",
      source: "planning-session",
      timestamp: "2026-05-14T11:50:00+08:00",
      confidence: 0.98,
      tags: ["privacy", "identity", "local-first"],
    },
    {
      id: "mem-002",
      kind: "decision",
      title: "Ollama-first laptop runtime",
      summary: "Ollama is the default local model runtime; LM Studio and vLLM/SGLang are adapters.",
      source: "planning-session",
      timestamp: "2026-05-14T11:54:00+08:00",
      confidence: 0.95,
      tags: ["models", "ollama", "laptop"],
    },
    {
      id: "mem-003",
      kind: "timeline",
      title: "Jarvis foundation created",
      summary: "The owned Jarvis monorepo foundation was started with strict guardrails.",
      source: "system",
      timestamp: "2026-05-14T12:00:00+08:00",
      confidence: 0.9,
      tags: ["timeline", "foundation"],
    },
  ],
  skills: [
    {
      id: "local-research",
      name: "Local Research",
      description: "Searches approved local documents, notes, PDFs, and indexed project files.",
      permissions: ["read-local"],
      source: "jarvis",
      enabled: true,
    },
    {
      id: "code-review",
      name: "Code Review",
      description: "Runs static analysis, test commands, and review checklists inside approved workspaces.",
      permissions: ["read-local", "write-local"],
      source: "ruflo-reference",
      enabled: true,
    },
    {
      id: "memory-dreaming",
      name: "Memory Dreaming",
      description: "Nightly consolidation, contradiction detection, and stale-memory pruning.",
      permissions: ["read-local", "write-local"],
      source: "openclaw-reference",
      enabled: true,
    },
  ],
  connectors: [
    {
      id: "filesystem",
      name: "Approved Folders",
      category: "software",
      permissions: ["read-local", "write-local", "delete-local"],
      dataTouched: ["documents", "code", "notes"],
      approvalRequired: ["delete-local", "irreversible-edit"],
      enabled: true,
      rollback: "best-effort",
    },
    {
      id: "ollama",
      name: "Ollama Runtime",
      category: "developer",
      permissions: ["read-local", "model-download"],
      dataTouched: ["local models", "prompts"],
      approvalRequired: ["model-download"],
      enabled: true,
      kind: "dev-tool",
      credentialStatus: "not-required",
      rollback: "none",
    },
    {
      id: "huggingface-local",
      name: "Hugging Face Local Cache",
      category: "developer",
      permissions: ["read-local", "model-download"],
      dataTouched: ["local model cache", "model metadata"],
      approvalRequired: ["model-download"],
      enabled: true,
      kind: "dev-tool",
      credentialStatus: "not-configured",
      rollback: "none",
    },
    {
      id: "social-outbox",
      name: "Social Outbox",
      category: "social",
      permissions: ["send-message", "post-social", "network"],
      dataTouched: ["messages", "contacts", "social posts"],
      approvalRequired: ["send-message", "post-social", "network"],
      enabled: false,
      kind: "social-outbox",
      credentialStatus: "not-required",
      rollback: "none",
    },
    {
      id: "discord",
      name: "Discord",
      category: "social",
      permissions: ["send-message", "network"],
      dataTouched: ["messages", "contacts", "channels"],
      approvalRequired: ["send-message", "network"],
      enabled: false,
      kind: "discord",
      credentialStatus: "not-configured",
      rollback: "none",
    },
    {
      id: "telegram",
      name: "Telegram",
      category: "social",
      permissions: ["send-message", "network"],
      dataTouched: ["messages", "contacts", "chats"],
      approvalRequired: ["send-message", "network"],
      enabled: false,
      kind: "telegram",
      credentialStatus: "not-configured",
      rollback: "none",
    },
    {
      id: "whatsapp",
      name: "WhatsApp",
      category: "social",
      permissions: ["send-message", "network"],
      dataTouched: ["messages", "contacts", "chats"],
      approvalRequired: ["send-message", "network"],
      enabled: false,
      kind: "whatsapp",
      credentialStatus: "not-configured",
      rollback: "none",
    },
    {
      id: "email",
      name: "Email",
      category: "social",
      permissions: ["send-message", "network"],
      dataTouched: ["messages", "contacts", "email metadata"],
      approvalRequired: ["send-message", "network"],
      enabled: false,
      kind: "email",
      credentialStatus: "not-configured",
      rollback: "none",
    },
    {
      id: "camera",
      name: "Camera Vision",
      category: "device",
      permissions: ["sensor-capture"],
      dataTouched: ["camera frames", "face identity", "room context"],
      approvalRequired: ["sensor-capture"],
      enabled: false,
      kind: "camera",
      credentialStatus: "not-required",
      rollback: "none",
    },
    {
      id: "screen",
      name: "Screen Awareness",
      category: "device",
      permissions: ["sensor-capture"],
      dataTouched: ["screen pixels", "OCR text", "app activity"],
      approvalRequired: ["sensor-capture"],
      enabled: false,
      kind: "screen",
      credentialStatus: "not-required",
      rollback: "none",
    },
    {
      id: "slack",
      name: "Slack",
      category: "social",
      permissions: ["send-message", "network"],
      dataTouched: ["messages", "contacts", "channels"],
      approvalRequired: ["send-message", "network"],
      enabled: false,
      kind: "slack",
      credentialStatus: "not-configured",
      rollback: "none",
    },
  ],
  pendingApprovals: [
    {
      id: "approval-001",
      title: "Enable continuous screen timeline capture",
      category: "sensor-capture",
      target: "screen timeline",
      reason: "Required for full past/present/future awareness and rewind views.",
      connectorId: "filesystem",
      agentId: "jarvis",
      dataTouched: ["screen content", "app activity", "timeline"],
    },
    {
      id: "approval-002",
      title: "Download Qwen3 Coder 7B through Ollama",
      category: "model-download",
      target: "qwen3-coder:7b",
      reason: "Enable deeper local coding and review workflows after benchmarking.",
      connectorId: "ollama",
      agentId: "planner",
      dataTouched: ["local model cache"],
    },
  ],
  mobilePairings: [],
  socialDrafts: [],
  toolStatuses: [],
  lastEvolutionReport:
    "Jarvis is in foundation mode: privacy kernel, local model registry, MemoryOS, AgentOS, connectors, and UI are being wired for safe growth.",
};
